### ISSUE TITLE
Need proper approach to add HTTP binding configs

### ISSUE THREAD

**Issue by milindaperera** [wso2/carbon-transports#127]
Need to figure out proper approach when binding the server at [1]

With current approach we get NPE [2] for requests when using IPV6

[1] https://github.com/wso2/carbon-transports/blob/master/http/netty/components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPTransportListener.java#L82

[2] 
[2016-11-01 14:17:33,292] ERROR {org.wso2.carbon.transport.http.netty.listener.CarbonHTTPServerInitializer} - Cannot Create SourceHandler java.lang.NullPointerException
        at org.wso2.carbon.transport.http.netty.listener.CarbonHTTPServerInitializer.initChannel(CarbonHTTPServerInitializer.java:149)
        at org.wso2.carbon.transport.http.netty.listener.CarbonHTTPServerInitializer.initChannel(CarbonHTTPServerInitializer.java:43)
        at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:133)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:356)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by milindaperera** [comment]
For temporary workaround solution refer [1]
[1] http://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/
